#!D:\PATH\NodeJS node

process.env.NODE_ENV = 'development';

const del = require('del');
const { fork } = require('child_process');
const path = require('path');
const { paths: appPath } = require('../config/utils');

const root = (...paths) => path.resolve(appPath.root, ...paths);

async function run() {
  await del(appPath.dll);
  await del(`${appPath.caches}/*.json`);

  const dllProcess = fork(appPath.webpackScript, [
    '--config',
    root('config', 'webpack.dll.js')
  ]);

  dllProcess.on('exit', function() {
    const serveProcess = fork(appPath.webpackScript, [
      'serve',
      '--config',
      root('config', 'webpack.dev.js')
    ]);
  });
}

run();